[package]
name = "tokio-busy-workers"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
futures = "0.3.28"
prettytable = "0.10.0"
tokio = { version = "1.28.0", features = ["rt", "time", "rt-multi-thread"] }
